### ISSUE TITLE
git clone does not work

### ISSUE THREAD

**Issue by ik0zy** [ahammadnafiz/Predicta#1]
$ git clone https://github.com/predicta/predicta.git
Cloning into 'predicta'...
remote: Repository not found.
fatal: repository 'https://github.com/predicta/predicta.git/' not found

I tried in different terminals and directories.

**Comment by ahammadnafiz** [comment]
My mistake, Now git clone will work, I update the readme, check it out or git clone https://github.com/ahammadnafiz/Predicta.git
